### ISSUE TITLE
Server Status

### ISSUE THREAD

**Issue by realistiqrp** [xliel/discord-fivem-api#7]
hello!
i want to check if the server is offline or online... so i try some code snippets.. xD

var ServerStatus = srv.setServerStatus();
if(ServerStatus == 'offline' {
//code
} else {
//code
}

Only this snippet does not work for some reason... so i hope anyone can help me out of this...

**Comment by realistiqrp** [comment]
I'm developing something, but if i got the solution i will drop it here ;)

**Comment by MrGriefs** [comment]
1. The issues section is for reporting problems with the library, not general code support.
1. The method is `getServerStatus`, not `setServerStatus`.
1. The `getServerStatus` method returns a [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), which must be awaited via [ES6 async/await](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await) or `Promise`'s standard callback methods, [`Promise#then`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)/[`Promise#catch`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch)./[`Promise#finally`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally).
